# Generated by Django 3.0.8 on 2020-07-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehimachalapp', '0007_destination_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
