# Generated by Django 3.0.8 on 2020-07-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehimachalapp', '0008_destination_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='content_credit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
