# Generated by Django 3.0.8 on 2020-07-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehimachalapp', '0009_destination_content_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
