# Generated by Django 3.0.8 on 2020-07-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehimachalapp', '0010_contactme'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='has_short_desc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destination',
            name='short_desc',
            field=models.TextField(blank=True, default=''),
        ),
    ]
