# Generated by Django 3.0.8 on 2020-07-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehimachalapp', '0014_auto_20200722_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='total_educated',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
