# Generated by Django 3.0.8 on 2020-07-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehimachalapp', '0017_accomodation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodation',
            name='address_details',
        ),
        migrations.RemoveField(
            model_name='accomodation',
            name='pricing_details',
        ),
        migrations.RemoveField(
            model_name='accomodation',
            name='show_website',
        ),
        migrations.AddField(
            model_name='accomodation',
            name='accomodation_image',
            field=models.ImageField(default='', upload_to='Accomodation/'),
            preserve_default=False,
        ),
    ]
