# Generated by Django 3.0.8 on 2020-07-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehimachalapp', '0025_auto_20200726_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_online_url',
            field=models.URLField(default=''),
        ),
    ]
