# Generated by Django 3.0.8 on 2020-08-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehimachalapp', '0029_contactforerror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='website_url',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
