# Generated by Django 3.0.8 on 2020-08-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehimachalapp', '0031_auto_20200806_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactforerror',
            name='image',
            field=models.ImageField(blank=True, upload_to='ErrorComplaints/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_source',
            field=models.TextField(default=''),
        ),
    ]
