# Generated by Django 3.0.8 on 2020-07-18 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehimachalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.ImageField(upload_to='DestinationImages/None')),
                ('image_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehimachalapp.Destination')),
            ],
        ),
    ]
