# Generated by Django 3.0.8 on 2020-07-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehimachalapp', '0002_destination_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file_name',
            field=models.CharField(default=50, max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(upload_to='DestinationImages/<django.db.models.fields.CharField>'),
        ),
    ]
