# Generated by Django 3.0.8 on 2020-07-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehimachalapp', '0003_auto_20200718_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(upload_to='DestinationImages/'),
        ),
    ]
