# Generated by Django 3.0.8 on 2020-07-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehimachalapp', '0004_auto_20200718_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file_name',
        ),
    ]
