# Generated by Django 3.0.8 on 2020-07-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehimachalapp', '0006_image_image_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='category',
            field=models.ManyToManyField(blank=True, to='ehimachalapp.DestinationCategory'),
        ),
    ]
