# Generated by Django 3.0.8 on 2020-07-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehimachalapp', '0012_auto_20200722_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='is_in_homepage',
            field=models.BooleanField(default=True),
        ),
    ]
