# Generated by Django 3.0.8 on 2020-07-22 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehimachalapp', '0013_auto_20200722_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='female_educated',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='destination',
            name='female_pc',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='destination',
            name='male_educated',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='destination',
            name='male_pc',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='destination',
            name='population',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='CategoryPhoto',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.ImageField(upload_to='CategoryImages/')),
                ('image_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehimachalapp.DestinationCategory')),
            ],
        ),
    ]
