# Generated by Django 3.0.8 on 2020-07-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehimachalapp', '0015_destination_total_educated'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='show_demographics',
            field=models.BooleanField(default=True),
        ),
    ]
