# Generated by Django 3.0.8 on 2020-07-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehimachalapp', '0018_auto_20200724_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
