# Generated by Django 3.0.8 on 2020-07-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehimachalapp', '0021_destination_show_hotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_title_image',
            field=models.BooleanField(default=False),
        ),
    ]
