# Generated by Django 3.0.8 on 2020-07-26 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehimachalapp', '0024_auto_20200726_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationvideo',
            name='video_destination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ehimachalapp.Destination'),
        ),
    ]
