# Generated by Django 3.0.8 on 2020-08-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehimachalapp', '0030_auto_20200801_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactforerror',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/ErrorComplaints/'),
        ),
    ]
